// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using time_keeper.Models;

namespace timekeeper.Migrations
{
    [DbContext(typeof(HolderContext))]
    [Migration("20190715030400_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("time_keeper.Models.Holder", b =>
                {
                    b.Property<string>("holder")
                        .ValueGeneratedOnAdd();

                    b.HasKey("holder");

                    b.ToTable("HoldingUser");
                });
#pragma warning restore 612, 618
        }
    }
}
